//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmallRss.Web.ServiceApi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="SmallRss.Api", Namespace="http://smallrss", ConfigurationName="ServiceApi.SmallRssApi")]
    public interface SmallRssApi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smallrss/SmallRss.Api/RefreshAllFeeds", ReplyAction="http://smallrss/SmallRss.Api/RefreshAllFeedsResponse")]
        void RefreshAllFeeds(int userAccountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smallrss/SmallRss.Api/RefreshAllFeeds", ReplyAction="http://smallrss/SmallRss.Api/RefreshAllFeedsResponse")]
        System.Threading.Tasks.Task RefreshAllFeedsAsync(int userAccountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smallrss/SmallRss.Api/RefreshFeed", ReplyAction="http://smallrss/SmallRss.Api/RefreshFeedResponse")]
        void RefreshFeed(int userAccountId, int feedId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://smallrss/SmallRss.Api/RefreshFeed", ReplyAction="http://smallrss/SmallRss.Api/RefreshFeedResponse")]
        System.Threading.Tasks.Task RefreshFeedAsync(int userAccountId, int feedId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmallRssApiChannel : SmallRss.Web.ServiceApi.SmallRssApi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmallRssApiClient : System.ServiceModel.ClientBase<SmallRss.Web.ServiceApi.SmallRssApi>, SmallRss.Web.ServiceApi.SmallRssApi {
        
        public SmallRssApiClient() {
        }
        
        public SmallRssApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmallRssApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmallRssApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmallRssApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RefreshAllFeeds(int userAccountId) {
            base.Channel.RefreshAllFeeds(userAccountId);
        }
        
        public System.Threading.Tasks.Task RefreshAllFeedsAsync(int userAccountId) {
            return base.Channel.RefreshAllFeedsAsync(userAccountId);
        }
        
        public void RefreshFeed(int userAccountId, int feedId) {
            base.Channel.RefreshFeed(userAccountId, feedId);
        }
        
        public System.Threading.Tasks.Task RefreshFeedAsync(int userAccountId, int feedId) {
            return base.Channel.RefreshFeedAsync(userAccountId, feedId);
        }
    }
}
